sudo: false
dist: trusty
language: c

addons:
  apt:
    packages:
    - gcc-arm-none-eabi
    - libnewlib-arm-none-eabi

script:
  - make -f Makefile.stm32
  - make clean
  - make
  - ./test_api.exe
  - ./test_unit.exe

notifications:
  webhooks:
    urls:
      - http://ci-bot.satoshilabs.com:5000/travis
    on_success: always
    on_failure: always
    on_start: always
